logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
    logback:
        rollingpolicy:
            max-file-size: 1MB
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1312
        url: jdbc:mysql://localhost:3306/fitshop_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_SQL: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            enabled: true
            max-request-size: 5MB

cloudinary:
    api-key: ${"246384523375955"}
    api-secret: ${"-3XXTmvZ4dFtYHEm6NqL4JvkhlM"}
    cloud-name: ${"ds3x8yju2"}